# Generated by Django 5.2.7 on 2025-10-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_completed_remove_task_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-priority", "due_date"]},
        ),
    ]
